# Generated by Django 4.2.7 on 2023-12-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('nombreUsuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreUsuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='VentaPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.promocion')),
                ('id_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.venta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=30)),
                ('codigo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.producto')),
                ('correo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_donacion', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('monto', models.CharField(max_length=30)),
                ('fecha', models.CharField(max_length=30)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fecha_inicio', models.CharField(max_length=30)),
                ('fecha_despacho', models.CharField(max_length=30)),
                ('fecha_recepcion', models.CharField(max_length=30)),
                ('id_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compraAhorra.venta')),
            ],
        ),
    ]
