# Generated by Django 4.2.7 on 2023-12-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compraAhorra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='correo',
            new_name='nombreUsuario',
        ),
        migrations.RenameField(
            model_name='usuariodonacion',
            old_name='correo',
            new_name='nombreUsuario',
        ),
        migrations.RenameField(
            model_name='usuarioproducto',
            old_name='correo',
            new_name='nombreUsuario',
        ),
    ]
