# Generated by Django 4.2.7 on 2023-12-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraAhorra', '0002_rename_correo_promocion_nombreusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
